image: python:3.8-slim

stages:
    - deploy

before_script:
    - pip install twine
    - python setup.py sdist

deploy_production:
    stage: deploy

    script:
        - twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD
    
    only:
        - tags