image: python:3.8-slim

stages:
    - deploy

before_script:
    - pip install twine
    - python setup.py sdist

deploy_production:
    stage: deploy
    variables:
        TWINE_USERNAME: $PRODUCTION_USERNAME
        TWINE_PASSWORD: $PRODUCTION_PASSWORD
    script:
        - python
        - import os
        - print(os.getenv($PRODUCTION_USERNAME))
        - quit()
    only:
        - tags